### ISSUE TITLE
Le texte en fin de Page...

### ISSUE THREAD

**Issue by RomainDugarin** [Sacrezar/Projecto-GF13-009NF-MOODLE-Mark-IV-Ros-ReXia-Cesi-Edition-Ultracompacto-WebSite-4.12-GEN-Aka-Aurelu#10]
Faut peut être rendre le tout plus lisible comme sur la version normal

![image](https://user-images.githubusercontent.com/33719373/65328638-0a4fa280-dbb7-11e9-90e7-55ebf2604aef.png)

--> 

![image](https://user-images.githubusercontent.com/33719373/65328682-25221700-dbb7-11e9-91ba-73d9c178bc10.png)

**Comment by Hveodrungr** [comment]
Peut etre le modifié et rajouter notre Copyright

**Comment by RomainDugarin** [comment]
peut être le mettre dans une bulle cowsay aussi...
![image](https://user-images.githubusercontent.com/33719373/65328852-906be900-dbb7-11e9-8aab-941192e436d3.png)
