### ISSUE TITLE
Une icone de couleurs non Validé par le code couleur

### ISSUE THREAD

**Issue by RomainDugarin** [Sacrezar/Projecto-GF13-009NF-MOODLE-Mark-IV-Ros-ReXia-Cesi-Edition-Ultracompacto-WebSite-4.12-GEN-Aka-Aurelu#15]
![image](https://user-images.githubusercontent.com/33719373/65329503-d9706d00-dbb8-11e9-8ef7-c00149a49bba.png)

est ce que on donnerait pas une couleur plus neutre a ce logo
genre:

![image](https://user-images.githubusercontent.com/33719373/65329603-1177b000-dbb9-11e9-9de3-c88ba0ac1db3.png)

**Comment by RomainDugarin** [comment]
Trouvé sur https://moodle-examens.cesi.fr/

Code:

entre balise < i > < /i >
class="icon fa fa-question-circle text-info fa-fw " title="Aide sur Rechercher des cours" aria-label="Aide sur Rechercher des cours" id="yui_3_17_2_1_1568984963149_140">

**Comment by IamClearlyJoking** [comment]
Ok très bien
