### ISSUE TITLE
Probleme de couleur en CCTL pour le menu de question

### ISSUE THREAD

**Issue by RomainDugarin** [Sacrezar/Projecto-GF13-009NF-MOODLE-Mark-IV-Ros-ReXia-Cesi-Edition-Ultracompacto-WebSite-4.12-GEN-Aka-Aurelu#24]
![image](https://user-images.githubusercontent.com/33719373/68849519-84da0180-06d2-11ea-9df2-6e5d5c30a858.png)

**Comment by Hveodrungr** [comment]
On a besoin de plus de données pour fix cette issue
Close
