### ISSUE TITLE
Rajouter l'ENT please

### ISSUE THREAD

**Issue by BuDorian** [Sacrezar/Projecto-GF13-009NF-MOODLE-Mark-IV-Ros-ReXia-Cesi-Edition-Ultracompacto-WebSite-4.12-GEN-Aka-Aurelu#26]
Rajouter l'ENT please

**Comment by s0tho** [comment]
https://github.com/Sacrezar/Exia-Theme-is-beautiful/commit/3d657ea9e49a4dcb0adb2ba39ce5e4ec2fe4fe4f

**Comment by s0tho** [comment]
Un premier code a été mis en place : https://github.com/Sacrezar/Exia-Theme-is-beautiful/tree/dev_ent

_**NB: L'addon n'est pas encore compatible avec Chrome (certaines couleurs seront présentes mais pas toutes)**_

Pour pouvoir le tester, il suffit de :

- Télécharger le zip de la branche dev_ent.
- Le décompresser

### 1. **Pour Firefox :**

- Copier coller `about:debugging#/runtime/this-firefox` en tant qu'URL
- Cliquer sur `Charger un module complémentaire temporaire` (n'importe quel fichier du dossier peut être sélectionné)
Vous devriez avoir ce résultat :
![image](https://user-images.githubusercontent.com/38185428/75323496-4fb68100-5875-11ea-9d3e-9c4db49e6538.png)

### 2. **Pour Chrome :**
- Copier coller `chrome://extensions/` en tant qu'URL
- Activer le mode développeur en haut à droite :
![image](https://user-images.githubusercontent.com/38185428/75323649-96a47680-5875-11ea-8a57-16fea2e10aff.png)
- Cliquer sur `Chargez l'extension non empaquetée` et sélectionnez le dossier
Vous devriez avoir quelque chose de similaire à ceci : 
![image](https://user-images.githubusercontent.com/38185428/75323778-d8352180-5875-11ea-81f9-6a78eef844d8.png)

**Comment by Hveodrungr** [comment]
https://github.com/Sacrezar/Exia-Theme-is-beautiful/commit/73d8dbd765ecd5ad7c4d654d6ac1655616bc1d56
Close #26
