### ISSUE TITLE
Readme Error: Contributors links missing

### ISSUE THREAD

**Issue by Hveodrungr** [Sacrezar/Projecto-GF13-009NF-MOODLE-Mark-IV-Ros-ReXia-Cesi-Edition-Ultracompacto-WebSite-4.12-GEN-Aka-Aurelu#31]
**Describe the bug**
The link of two of the contributors does not exist

**To Reproduce**
1. Go to 'ReadMe'
2. See error

**Expected behavior**
Louis and Dronai should have links

**Comment by Hveodrungr** [comment]
https://github.com/Sacrezar/Exia-Theme-is-beautiful/commit/aa42fa27daf11fd0410899c1214e0e7d90a5af49
Added louis's link still dronai link missing

**Comment by s0tho** [comment]
**Proposition:**
Add Antoine to the contributors

**Comment by Hveodrungr** [comment]
Add Antoine to the contributors : https://github.com/Sacrezar/Exia-Theme-is-beautiful/commit/495fc4a4f7cc9cfcd4623742eafb2dc700f8f31e

Add Dronai link to the contributors : https://github.com/Sacrezar/Exia-Theme-is-beautiful/commit/ba553426d18ba5bbc9b79154cb92d318311492c2

**Comment by Hveodrungr** [comment]
Add Antoine link : https://github.com/AlphaCodeCorp/Exia-Theme-is-beautiful/commit/edb1baa54257d529159ec25728d1db24620721b6
